// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: nodeagent/direct/v1/alertstream.proto

package directv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AlertStream_Subscribe_FullMethodName = "/nodeagent.direct.v1.AlertStream/Subscribe"
)

// AlertStreamClient is the client API for AlertStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlertStreamClient interface {
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AlertBatch], error)
}

type alertStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewAlertStreamClient(cc grpc.ClientConnInterface) AlertStreamClient {
	return &alertStreamClient{cc}
}

func (c *alertStreamClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AlertBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AlertStream_ServiceDesc.Streams[0], AlertStream_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, AlertBatch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AlertStream_SubscribeClient = grpc.ServerStreamingClient[AlertBatch]

// AlertStreamServer is the server API for AlertStream service.
// All implementations must embed UnimplementedAlertStreamServer
// for forward compatibility.
type AlertStreamServer interface {
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[AlertBatch]) error
	mustEmbedUnimplementedAlertStreamServer()
}

// UnimplementedAlertStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAlertStreamServer struct{}

func (UnimplementedAlertStreamServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[AlertBatch]) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedAlertStreamServer) mustEmbedUnimplementedAlertStreamServer() {}
func (UnimplementedAlertStreamServer) testEmbeddedByValue()                     {}

// UnsafeAlertStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlertStreamServer will
// result in compilation errors.
type UnsafeAlertStreamServer interface {
	mustEmbedUnimplementedAlertStreamServer()
}

func RegisterAlertStreamServer(s grpc.ServiceRegistrar, srv AlertStreamServer) {
	// If the following call pancis, it indicates UnimplementedAlertStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AlertStream_ServiceDesc, srv)
}

func _AlertStream_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AlertStreamServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, AlertBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AlertStream_SubscribeServer = grpc.ServerStreamingServer[AlertBatch]

// AlertStream_ServiceDesc is the grpc.ServiceDesc for AlertStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlertStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nodeagent.direct.v1.AlertStream",
	HandlerType: (*AlertStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _AlertStream_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nodeagent/direct/v1/alertstream.proto",
}
