// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: nodeagent/direct/v1/alertstream.proto

package directv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SinceSeq      uint64                 `protobuf:"varint,1,opt,name=since_seq,json=sinceSeq,proto3" json:"since_seq,omitempty"`
	MaxBatch      uint32                 `protobuf:"varint,2,opt,name=max_batch,json=maxBatch,proto3" json:"max_batch,omitempty"`
	ProducerEpoch string                 `protobuf:"bytes,3,opt,name=producer_epoch,json=producerEpoch,proto3" json:"producer_epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_nodeagent_direct_v1_alertstream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_direct_v1_alertstream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_nodeagent_direct_v1_alertstream_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetSinceSeq() uint64 {
	if x != nil {
		return x.SinceSeq
	}
	return 0
}

func (x *SubscribeRequest) GetMaxBatch() uint32 {
	if x != nil {
		return x.MaxBatch
	}
	return 0
}

func (x *SubscribeRequest) GetProducerEpoch() string {
	if x != nil {
		return x.ProducerEpoch
	}
	return ""
}

type AlertBatch struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OldestSeq        uint64                 `protobuf:"varint,1,opt,name=oldest_seq,json=oldestSeq,proto3" json:"oldest_seq,omitempty"`
	NewestSeq        uint64                 `protobuf:"varint,2,opt,name=newest_seq,json=newestSeq,proto3" json:"newest_seq,omitempty"`
	Gap              bool                   `protobuf:"varint,3,opt,name=gap,proto3" json:"gap,omitempty"`
	DroppedSinceLast uint64                 `protobuf:"varint,4,opt,name=dropped_since_last,json=droppedSinceLast,proto3" json:"dropped_since_last,omitempty"`
	SentAtNs         int64                  `protobuf:"varint,5,opt,name=sent_at_ns,json=sentAtNs,proto3" json:"sent_at_ns,omitempty"`
	NodeAgentVersion string                 `protobuf:"bytes,6,opt,name=node_agent_version,json=nodeAgentVersion,proto3" json:"node_agent_version,omitempty"`
	Alerts           []*Alert               `protobuf:"bytes,7,rep,name=alerts,proto3" json:"alerts,omitempty"`
	ProducerEpoch    string                 `protobuf:"bytes,8,opt,name=producer_epoch,json=producerEpoch,proto3" json:"producer_epoch,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AlertBatch) Reset() {
	*x = AlertBatch{}
	mi := &file_nodeagent_direct_v1_alertstream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertBatch) ProtoMessage() {}

func (x *AlertBatch) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_direct_v1_alertstream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertBatch.ProtoReflect.Descriptor instead.
func (*AlertBatch) Descriptor() ([]byte, []int) {
	return file_nodeagent_direct_v1_alertstream_proto_rawDescGZIP(), []int{1}
}

func (x *AlertBatch) GetOldestSeq() uint64 {
	if x != nil {
		return x.OldestSeq
	}
	return 0
}

func (x *AlertBatch) GetNewestSeq() uint64 {
	if x != nil {
		return x.NewestSeq
	}
	return 0
}

func (x *AlertBatch) GetGap() bool {
	if x != nil {
		return x.Gap
	}
	return false
}

func (x *AlertBatch) GetDroppedSinceLast() uint64 {
	if x != nil {
		return x.DroppedSinceLast
	}
	return 0
}

func (x *AlertBatch) GetSentAtNs() int64 {
	if x != nil {
		return x.SentAtNs
	}
	return 0
}

func (x *AlertBatch) GetNodeAgentVersion() string {
	if x != nil {
		return x.NodeAgentVersion
	}
	return ""
}

func (x *AlertBatch) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

func (x *AlertBatch) GetProducerEpoch() string {
	if x != nil {
		return x.ProducerEpoch
	}
	return ""
}

type Alert struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Seq                   uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Hostname              string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	EventTimeNs           int64                  `protobuf:"varint,3,opt,name=event_time_ns,json=eventTimeNs,proto3" json:"event_time_ns,omitempty"`
	RuleId                string                 `protobuf:"bytes,4,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Message               string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	BaseRuntimeMetadata   []byte                 `protobuf:"bytes,6,opt,name=base_runtime_metadata,json=baseRuntimeMetadata,proto3" json:"base_runtime_metadata,omitempty"`
	RuntimeK8SDetails     []byte                 `protobuf:"bytes,7,opt,name=runtime_k8s_details,json=runtimeK8sDetails,proto3" json:"runtime_k8s_details,omitempty"`
	RuntimeProcessDetails []byte                 `protobuf:"bytes,8,opt,name=runtime_process_details,json=runtimeProcessDetails,proto3" json:"runtime_process_details,omitempty"`
	CloudMetadata         []byte                 `protobuf:"bytes,9,opt,name=cloud_metadata,json=cloudMetadata,proto3" json:"cloud_metadata,omitempty"`
	MitreTactic           string                 `protobuf:"bytes,10,opt,name=mitre_tactic,json=mitreTactic,proto3" json:"mitre_tactic,omitempty"`
	MitreTechnique        string                 `protobuf:"bytes,11,opt,name=mitre_technique,json=mitreTechnique,proto3" json:"mitre_technique,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_nodeagent_direct_v1_alertstream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_direct_v1_alertstream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_nodeagent_direct_v1_alertstream_proto_rawDescGZIP(), []int{2}
}

func (x *Alert) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Alert) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Alert) GetEventTimeNs() int64 {
	if x != nil {
		return x.EventTimeNs
	}
	return 0
}

func (x *Alert) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *Alert) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Alert) GetBaseRuntimeMetadata() []byte {
	if x != nil {
		return x.BaseRuntimeMetadata
	}
	return nil
}

func (x *Alert) GetRuntimeK8SDetails() []byte {
	if x != nil {
		return x.RuntimeK8SDetails
	}
	return nil
}

func (x *Alert) GetRuntimeProcessDetails() []byte {
	if x != nil {
		return x.RuntimeProcessDetails
	}
	return nil
}

func (x *Alert) GetCloudMetadata() []byte {
	if x != nil {
		return x.CloudMetadata
	}
	return nil
}

func (x *Alert) GetMitreTactic() string {
	if x != nil {
		return x.MitreTactic
	}
	return ""
}

func (x *Alert) GetMitreTechnique() string {
	if x != nil {
		return x.MitreTechnique
	}
	return ""
}

var File_nodeagent_direct_v1_alertstream_proto protoreflect.FileDescriptor

const file_nodeagent_direct_v1_alertstream_proto_rawDesc = "" +
	"\n" +
	"%nodeagent/direct/v1/alertstream.proto\x12\x13nodeagent.direct.v1\"s\n" +
	"\x10SubscribeRequest\x12\x1b\n" +
	"\tsince_seq\x18\x01 \x01(\x04R\bsinceSeq\x12\x1b\n" +
	"\tmax_batch\x18\x02 \x01(\rR\bmaxBatch\x12%\n" +
	"\x0eproducer_epoch\x18\x03 \x01(\tR\rproducerEpoch\"\xb1\x02\n" +
	"\n" +
	"AlertBatch\x12\x1d\n" +
	"\n" +
	"oldest_seq\x18\x01 \x01(\x04R\toldestSeq\x12\x1d\n" +
	"\n" +
	"newest_seq\x18\x02 \x01(\x04R\tnewestSeq\x12\x10\n" +
	"\x03gap\x18\x03 \x01(\bR\x03gap\x12,\n" +
	"\x12dropped_since_last\x18\x04 \x01(\x04R\x10droppedSinceLast\x12\x1c\n" +
	"\n" +
	"sent_at_ns\x18\x05 \x01(\x03R\bsentAtNs\x12,\n" +
	"\x12node_agent_version\x18\x06 \x01(\tR\x10nodeAgentVersion\x122\n" +
	"\x06alerts\x18\a \x03(\v2\x1a.nodeagent.direct.v1.AlertR\x06alerts\x12%\n" +
	"\x0eproducer_epoch\x18\b \x01(\tR\rproducerEpoch\"\xaf\x03\n" +
	"\x05Alert\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\"\n" +
	"\revent_time_ns\x18\x03 \x01(\x03R\veventTimeNs\x12\x17\n" +
	"\arule_id\x18\x04 \x01(\tR\x06ruleId\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x122\n" +
	"\x15base_runtime_metadata\x18\x06 \x01(\fR\x13baseRuntimeMetadata\x12.\n" +
	"\x13runtime_k8s_details\x18\a \x01(\fR\x11runtimeK8sDetails\x126\n" +
	"\x17runtime_process_details\x18\b \x01(\fR\x15runtimeProcessDetails\x12%\n" +
	"\x0ecloud_metadata\x18\t \x01(\fR\rcloudMetadata\x12!\n" +
	"\fmitre_tactic\x18\n" +
	" \x01(\tR\vmitreTactic\x12'\n" +
	"\x0fmitre_technique\x18\v \x01(\tR\x0emitreTechniqueJ\x04\b\f\x10\rR\frule_version2d\n" +
	"\vAlertStream\x12U\n" +
	"\tSubscribe\x12%.nodeagent.direct.v1.SubscribeRequest\x1a\x1f.nodeagent.direct.v1.AlertBatch0\x01BMZKgithub.com/k8sstormcenter/nodeagent-direct-api/nodeagent/direct/v1;directv1b\x06proto3"

var (
	file_nodeagent_direct_v1_alertstream_proto_rawDescOnce sync.Once
	file_nodeagent_direct_v1_alertstream_proto_rawDescData []byte
)

func file_nodeagent_direct_v1_alertstream_proto_rawDescGZIP() []byte {
	file_nodeagent_direct_v1_alertstream_proto_rawDescOnce.Do(func() {
		file_nodeagent_direct_v1_alertstream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nodeagent_direct_v1_alertstream_proto_rawDesc), len(file_nodeagent_direct_v1_alertstream_proto_rawDesc)))
	})
	return file_nodeagent_direct_v1_alertstream_proto_rawDescData
}

var file_nodeagent_direct_v1_alertstream_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nodeagent_direct_v1_alertstream_proto_goTypes = []any{
	(*SubscribeRequest)(nil), // 0: nodeagent.direct.v1.SubscribeRequest
	(*AlertBatch)(nil),       // 1: nodeagent.direct.v1.AlertBatch
	(*Alert)(nil),            // 2: nodeagent.direct.v1.Alert
}
var file_nodeagent_direct_v1_alertstream_proto_depIdxs = []int32{
	2, // 0: nodeagent.direct.v1.AlertBatch.alerts:type_name -> nodeagent.direct.v1.Alert
	0, // 1: nodeagent.direct.v1.AlertStream.Subscribe:input_type -> nodeagent.direct.v1.SubscribeRequest
	1, // 2: nodeagent.direct.v1.AlertStream.Subscribe:output_type -> nodeagent.direct.v1.AlertBatch
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_nodeagent_direct_v1_alertstream_proto_init() }
func file_nodeagent_direct_v1_alertstream_proto_init() {
	if File_nodeagent_direct_v1_alertstream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nodeagent_direct_v1_alertstream_proto_rawDesc), len(file_nodeagent_direct_v1_alertstream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nodeagent_direct_v1_alertstream_proto_goTypes,
		DependencyIndexes: file_nodeagent_direct_v1_alertstream_proto_depIdxs,
		MessageInfos:      file_nodeagent_direct_v1_alertstream_proto_msgTypes,
	}.Build()
	File_nodeagent_direct_v1_alertstream_proto = out.File
	file_nodeagent_direct_v1_alertstream_proto_goTypes = nil
	file_nodeagent_direct_v1_alertstream_proto_depIdxs = nil
}
